//let a = 2;

try {
    let c = a + 1;
} catch (error) {
    console.log("Algo deu errado: " + error);
} finally {
    console.log("Executou!");
}

console.log('teste');